spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USER}
    password: ${AWS_DB_PASS}
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jwt:
    token:
      secretKey: ${JWT_SECRET_KEY}
      expiration: # (만료) 시간 설정은 ms단위
        access: 14400000 # 4시간(보통 1시간~4시간 단위를 많이 채택)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao

cloud:
  aws:
    s3:
      bucket: umc-8th-week12
      path:
        review: reviews
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}